name: Confiture de quetsches
description: Cuisson à feu doux dans une bassine en cuivre.
categories:
  - epicerie_sucree 
price:
  id: price_1KLZGeBVac9AX8WwH0h5KEvx
  amount: 4
  currency: '€'
allergens: Gluten, lactose, œufs, fruits à coques.
ingredients: 82% quetsches°, 18% sucre*.
weight: 212
stripe_id: prod_L1cV2ianay5gqZ