name: Palets
description:
categories:
  - epicerie_sucree 
price:
  id: price_1KJJeDBVac9AX8Ww1sMOsYOk
  amount: 4.75
  currency: '€'
allergens: Gluten, lactose, œufs, fruits à coques.
ingredients: farine de blé*°, beurre*, sucre*, jaunes d'oeufs frais*°, poudre à lever*, sel*.
weight: 200
stripe_id: prod_KzIEbHMqv9Bim2